travis:
  secure:
    BINSTAR_TOKEN: zQAPHpZpm3LjPqyuH72vDjyXln0gPYuRpQP2ES8Smem7yx++eIT//XVR+W3Zbw7EZ0jlwyflPebHI1nuWEU0X4+XqdqRnz4Br7OzjW5460OymmGjvB4NLOq/E8f4wuR0liQh9NM5sMrN9yJy9Q1Iy9L9BJVfDKfkjEXEZRAAjtAudX4fZYrJxUl7Jl5pJLJTwF4eZkF9OBZY/Tg4jAV+GQT8+xp6Tio6/oC9T7nyUa58yLXpjH1pvGNwTyUttWqBfW/1UbDws/Z385Yye/TZFh8YTJ3owA2+7ps7zMjzaOJMJeITu6gtBRz4Wdb1WDP1zXqY5LwV/YBwXLN+rr5ZPJcymp/IsAmgyI2pWGhA6ebpX0lKEaJZPnNUCTIplMQzL8ssJL/g+pPJNTTZKlJFHFGhpy3YUHe4zm8ACvhLxkEY6HtgSf+0UWEhRiDQEPz77/TJMNxELha0KOBtslrv+mbu/dtxCVr3oAT61IZ/ysV8XtN9xK+gCh4hC05ah8rkQg38XZZi27Y9FZm49aVpWvATvbXI6hJZwfN7wl8Z/lKj4eOVwOiPHff2onO59MhzMXP2LFXz2BAuYA//QTm7OD9S1di5m+AGO4MyvB59SqBak/8ibdVYAatdXgRDN/BiSyAzt1e+FZF6e9CZUExfxniYduAmBSsZqZn36RhDTJ4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
