travis:
  secure:
    BINSTAR_TOKEN: 5ZdJ101a+rfyOTBG49YO3S2Stsc7Dd3mOVukHLJPRGJaPueTthDTO0n6tXw0UHpW0I+5lbNCrDEJnDFxme2pm8y3x5Zkc7q8AgdX9MJVJMoxkeB3CSpZyL5rjB/AA220vIcq8w+EHTt6/NnS4ltTWGXPKsQecoVeU3B6nuREUmuejJ0SWUIngbAJg+w9/znRUi0F8WoLJvQTZho+tZIZJOKLr3HWCb0z+07s5cRxdGFZk5NL2//JfywFK03G0DgL8AUmHSFKq2tvIx7ZIsao1E1ASegFLy1m6wBbeCnNU4CbRol4uusu3WsWy9iAq8rQmpj6TcLZscx2abA+SPi5dB66X4KRyb5Ff7DYHjodxBv05aj19FsppEN2EgQGS8rvo0sh85PuZG7xLhgf+hc0tlPqnOoShVLqM9BbF94cVy3t5XpI3K+89ZNZH2EZd/1KqB2iETveoRHHAWbQqeT9zAO2+RZa0DfOUJTzyHoj9B2jwXFG23TAF1sJp191VgdI6ojyNnKuT60CJHg/Kt4VvjxVjK1liVxl1ctnR0xRFKCP8cA9rRf3WhDmB3O4JhLwdOMzdzyNrTtADVqmlkZh4XWmxaISFW0XOFmAk/zMa8PViqICX6lt7z6vj20NzO3JF5Ju1lAuipS5hSJlOS0CPdS1zD0Ki7u33AjDgz38H3g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
